Add picross (nonogram) game
Wolfyxon/3ds-web-stuff pull request #84
Opened 2024-06-12 19:51 UTC by basic-experimental

This is a picross puzzle player. It takes the puzzles in the form of [`.non` files](https://github.com/mikix/nonogram-db/blob/master/FORMAT.md). Currently, this is not ready to be merged, as it is missing many features and doesn't look great. I would appreciate feedback on the design direction and other features.
Currently, there is no level selector, so it will load `demo.non` as soon as the page is loaded. So far, it seems the only program on the website that has a selector like this would be the barcode generator. Should I try to keep it consistent with that, or do something new?
It is possible to make a level generator, but I find it way less fun when there isn't any theme to the completed puzzle. That does bring the question of where to get the puzzles. The [repo that the format information is in](https://github.com/mikix/nonogram-db) also contains puzzles with various licenses. This is where `demo.non` came from. Should I just use some of those? I could also create some myself.

In case you don't want to solve the puzzle yourself, [click here for the solution](https://github.com/Wolfyxon/3ds-web-stuff/assets/169532384/b0ddd1aa-f38e-445a-bd76-a44a9796cbe8)

2024-06-13 02:53 UTC, Trickiy commented
Some ideas for the direction 1.) Should you be consistent with the barcode generator? I think that there should be some experimentation. As having all games having a samey look to it would make things bland looking and repetitive. A idea I have is having the menus be a pixlated grid. That would slide the direction of were the page is at, and have the text be a retro pixlated looking too. While having what is hovered over pop out a bit, do a little hop, and then rotate to the left and right a little. 2.) Where should the puzzles be obtained? Use some of what is in the repo as a starting base with your own (If I can find a way to make pixel art within my restricted browser. I will give some screenshots for ideas.) and add the generator as endgame content.

2024-06-16 05:42 UTC, magiczocker10 commented
@basic-experimental @Trickiy  Do you have discord for easier communication?

2024-06-16 14:18 UTC, Trickiy commented
> @basic-experimental @Trickiy Do you have discord for easier communication?

I'm in a bad position at the moment sadly so no I do not. When I am in a better position I  will have discord, but it would be faster if brain dead Biden doesn't win the election. (Wich is very likely due to curruption in the gov at the moment I've heard.) As I'd be able to get a job sooner.

2024-06-22 00:39 UTC, basic-experimental commented
> @basic-experimental @Trickiy Do you have discord for easier communication?

I do. I am "das904."

Sorry for the wait, I wasn't able to respond.

2024-06-25 23:56 UTC, Trickiy commented
> @basic-experimental @Trickiy Do you have discord for easier communication?

I am happy to say that I managed to find a way to access discord within my overly restricted sandbox browser. So here's my username trickiidude.

2024-06-28 00:08 UTC, Trickiy commented
Basic could you add the ability to navigate the menu with the d-pad and press a to enter the level.

2024-07-08 00:41 UTC, basic-experimental commented
All right, I'm going to mark this as ready for review now. Only the tutorial levels have been made at the moment, but the game works, at least on new 3ds. I don't think that the CSS transform effects should make any difference to browsers without it, and I think the rest of the code is fairly compatible.

2024-07-09 09:45 UTC, Wolfyxon requested changes

2024-07-09 09:45 UTC, Wolfyxon commented on games/picross/picross.js
> +	function requestText(url, callback){
`requestText()` is redundant. **scripts/lib/net.js** has `httpGet()`

2024-07-09 09:45 UTC, Wolfyxon commented on games/picross/picross.js
> +	String.prototype.startsWith = function (str) { // This is a polyfill
Polyfills should be in **global.js**

2024-07-09 11:39 UTC, basic-experimental commented
Oh oops, I didn’t mean to do that. Sorry! I’ll get on with fixing those now.

2024-07-09 12:38 UTC, Wolfyxon commented
Please replace `requestText()` with `net.httpGet()`. It's not the same name, and it got moved to a namespace.

2024-07-09 12:42 UTC, Wolfyxon commented
Oh also, the text doesn't fully fit on the top screen.
![image](https://github.com/Wolfyxon/3ds-web-stuff/assets/58263600/521093ae-ec14-4e88-ac9a-a1207fc4a99f)
(ignore the red line)

2024-07-09 12:48 UTC, basic-experimental commented
Unfortunately I need to leave for something now and will be away for seven hours. I will try to fix those when I come back.

2024-07-09 13:12 UTC, Wolfyxon commented
Alright that's fine

2024-07-09 20:17 UTC, basic-experimental commented
I've finished with those changes now and tested them again. It all seems good. A real n3DS still has a tiny bit of text overflow on Tutorial-2, but it is still easily readable.

2024-07-09 21:52 UTC, Wolfyxon approved these changes
Looks good

2024-07-09 22:01 UTC, merged